# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Tesla Ble to Mqtt"
description: "Application to monitor and control Tesla vehicles over BLE with Home assistant"
version: "0.3.8"
slug: "tb2m"
init: false
apparmor: true
url: https://github.com/Lenart12/TeslaBle2Mqtt-addon
host_dbus: true
host_network: true
privileged: [NET_ADMIN]
panel_icon: mdi:car-wireless
services:
  - mqtt:want
discovery:
  - tb2m # TeslaBle2Mqtt
  - tbhp # TeslaBleHttpProxy
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  vins: null
ingress: true
ingress_port: 0
schema:
  vins:
    - match(^[A-Z0-9]{17}$)
  mqtt_host: str?
  mqtt_port: port?
  mqtt_user: str?
  mqtt_pass: password?
  mqtt_qos: list(0|1|2)?
  proxy_port: port?
  proxy_url: str?
  bt_adapter: match(^hci\d+$)?
  raw_hci: bool?
  scan_timeout: int?
  cache_max_age: int?
  poll_interval: int?
  poll_interval_charging: int?
  poll_interval_disconnected: int?
  fast_poll_time: int?
  max_charging_amps: int(5,48)?
  mqtt_prefix: match(^[-\w\d_]+$)?
  discovery_prefix: str?
  log_level: list(DEBUG_ALL|DEBUG|INFO|WARN|ERROR|FATAL)?
